
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author elena
 */
public class FechaHoraPanel extends JFrame {

    private final String mensajeNoCargado = "No ha escogido el archivo a ejecutar o la fecha de ejecución";

    /**
     * Creates new form PanelPruebas
     */
    public FechaHoraPanel() {
        initComponents();
        this.labelCargado.setHorizontalAlignment(SwingConstants.CENTER);
        /*
        if (this.fechaHoraDigital1.getFilePath() == null
                || this.fechaHoraDigital1.getFechaEjecucion() == null) {
            JOptionPane.showMessageDialog(null, this.mensajeNoCargado);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaHoraDigital1 = new componente.FechaHoraDigital();
        buttonCargar = new javax.swing.JButton();
        labelCargado = new javax.swing.JLabel();

        fechaHoraDigital1.setFilePath(new java.io.File("C:\\Program Files\\Notepad++\\notepad++.exe"));
        fechaHoraDigital1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fechaHoraDigital1.setFormato24h(true);

        buttonCargar.setText("Cargar");
        buttonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarActionPerformed(evt);
            }
        });

        labelCargado.setBackground(new java.awt.Color(255, 0, 51));
        labelCargado.setText("NO CARGADO");
        labelCargado.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaHoraDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCargado, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCargar)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(fechaHoraDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCargar)
                    .addComponent(labelCargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(153, 153, 153))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCargarActionPerformed
        if (this.fechaHoraDigital1.getFilePath() != null
                && this.fechaHoraDigital1.getFechaEjecucion() != null) {
            this.labelCargado.setBackground(Color.GREEN);
            this.labelCargado.setText("CARGADO");
        } else {
            JOptionPane.showMessageDialog(null, this.mensajeNoCargado);
        }
    }//GEN-LAST:event_buttonCargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCargar;
    private componente.FechaHoraDigital fechaHoraDigital1;
    private javax.swing.JLabel labelCargado;
    // End of variables declaration//GEN-END:variables
}
